[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "8gc7QHvsreuPTUrYpJ7dJxr6c8UB8kapeLW9Uoot8G1g"
k3n = "7EsEmSeRQ98ni2qed55nfMFYyD1omasLPsRn7jeWL7jF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tungxuan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
